### ISSUE TITLE
Unintended behavior

### ISSUE THREAD

**Issue by Nour-MK** [felladrin/windows-timelapse-toolkit#9]
### Bug description

Screenshots seem to be taken only from the upper left corner of my screen. 

### Steps to reproduce

Nothing special. Exactly the steps given to us in the documentation. I tried it before changing any configurations and after some tweaking; both cases still only take a screenshot of the upper left corner.

### Expected behavior

Take a screenshot of the whole monitor, as you usually would.
No I'm not currently using a dual monitor setup - so these complications are not on the table.

### Device info

HP Envy x360

### Additional context

I will be sure to reply to this issue if I figure out a way to fix it. There should be a way as I can take normal screenshots using windows' snip and ShareX. Also, I'm quite invested in the timelapse idea.

**Comment by felladrin** [comment]
That's interesting! Thanks for reporting!

There was a PR years ago that addressed a similar issue:

- https://github.com/felladrin/windows-timelapse-toolkit/pull/6

My guess is that Windows released some new feature related to the screen scaling that isn't supported by the 6-yo [screenCapture.exe](https://github.com/felladrin/windows-timelapse-toolkit/tree/b9a6c8fee5a837abee90c5a2dded7f51ddf2b9f8/tools).

Before that PR, I [used to recommend users to use `Windows10_DPI_FIX.exe`](https://github.com/felladrin/windows-timelapse-toolkit/pull/6/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L42-L43) to fix issues related to screen scaling, but I'm not sure if this would work nowadays.

Unfortunately, I'm not using Windows anymore. Let's leave this issue open in the hope someone can come up with an idea to solve it 🙏 

P.S. I once started rewriting windows-timelapse-toolkit using https://github.com/jangxx/node-win-desktop-duplication for capturing the screen. This should be a good starting point; I know it handles the screen scaling correctly due to the usage of [Windows' Desktop Duplication API](https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api).

**Comment by felladrin** [comment]
Ah, I just noticed one thing: I haven't made a release after https://github.com/felladrin/windows-timelapse-toolkit/pull/6 was merged.

Could you confirm if you are using [v1.1.0](https://github.com/felladrin/windows-timelapse-toolkit/releases/tag/v1.1.0) or the `main` branch of a clone of this repository?

If you're using v1.1.0, that might be the reason of the issue, and you should try [downloading `master`](https://github.com/felladrin/windows-timelapse-toolkit/archive/refs/heads/master.zip) and running it instead. If it works, I'll update the Readme.

**Comment by Nour-MK** [comment]
Yep, using v1.1.0; got it from the releases section. 
<img width="445" alt="chrome_RnHrr9nf0e" src="https://github.com/felladrin/windows-timelapse-toolkit/assets/123479685/5f67c91d-ad53-4e93-9cc2-98e20abf74af">

Onto downloading the master!

**Comment by Nour-MK** [comment]
Downloaded the master, everything works as expected! Cheers (and congrats on this handy little tool I really appreciate it)! 🥳

**Comment by felladrin** [comment]
Awesome, thank you for confirming!
I'll update the readme and get a new release out right away.
